services:
  - type: web
    name: spiritual-lessons
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: spiritual-lessons-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false

databases:
  - name: spiritual-lessons-db
    databaseName: spiritual_lessons
    user: spiritual_user